language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

services:
  - redis-server

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - ./gradlew clean build -Djasypt.encryptor.password=testjasyptencodepass

before_deploy:
  - zip -r springboot-temple-manager *
  - mkdir -p deploy
  - mv springboot-temple-manager.zip deploy/springboot-temple-manager.zip

notifications:
  email:
    recipients:
      - ryukiyoun@naver.com

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboottest-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: ryukiyoun/manager
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboottest-deploy
    key: springboot-temple-manager.zip
    bundle_type: zip
    application: springboot-temple-manager
    deployment_group: springboot-temple-manager
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: ryukiyoun/manager
      branch: master